<?xml version="1.0" encoding="UTF-8"?><testrun name="TestRatajList" project="BT-Library-Java" tests="29" started="29" failures="6" errors="0" ignored="0">
  <testsuite name="bt.tests.core.collections.dataTypes.TestRatajList" time="0.012">
    <testcase name="test_CTOR_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_CTOR_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_add_On1size_Expect_size2" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_add_On2size_Expect_size3" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_add_On3size_Expect_size4" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_add_Onnull_Expect_size1" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_attachAfter_0_On1size_Expect_size2" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_attachAfter_0_On2size_Expect_size3" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_attachAfter_0_OnNullOrEmpty_Expect_size1" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_delete_On1size_Expect_size0" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_delete_On1size_Expect_size1" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_delete_On2size_Expect_size1" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_delete_On3size_Expect_size2" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_delete_Onnull_Expect_size0" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_druk_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_druk_3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_druk_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_get_0_On1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.004">
      <failure>junit.framework.AssertionFailedError: expected:&lt;0&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_0_On1size_true(TestRatajList.java:260)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_0_On2size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;0&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_0_On2size_true(TestRatajList.java:283)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_0_On3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;0&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_0_On3size_true(TestRatajList.java:356)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_0_OnNull_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_get_1_On2size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;1&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_1_On2size_true(TestRatajList.java:306)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_1_On3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0">
      <failure>junit.framework.AssertionFailedError: expected:&lt;1&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_1_On3size_true(TestRatajList.java:383)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_2_On2size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_get_2_On3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected:&lt;2&gt; but was:&lt;-1&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotEquals(Assert.java:329)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:78)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:234)&#13;
	at junit.framework.Assert.assertEquals(Assert.java:241)&#13;
	at junit.framework.TestCase.assertEquals(TestCase.java:409)&#13;
	at bt.tests.core.collections.dataTypes.TestRatajList.test_get_2_On3size_true(TestRatajList.java:410)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_get_3_On3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_maxVal_1size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_maxVal_3size_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
    <testcase name="test_maxVal_null_true" classname="bt.tests.core.collections.dataTypes.TestRatajList" time="0.0"/>
  </testsuite>
</testrun>
