<?xml version="1.0" encoding="UTF-8"?><testrun name="TestArrayList" project="BT-Library-Java" tests="35" started="35" failures="4" errors="2" ignored="0">
  <testsuite name="bt.tests.core.collections.dataTypes.TestArrayList" time="0.062">
    <testcase name="test_CTOR_emptyList_size0" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_add_NotEmptyList_size2" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_add_NotEmptyList_size3" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_add_emptyList_size1" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_clear_empty_size0" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_clear_notEmpty_size0" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_contains_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_contains_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_contains_notEmpty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_delete_byIdx_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:55)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.Assert.assertFalse(Assert.java:39)&#13;
	at junit.framework.Assert.assertFalse(Assert.java:47)&#13;
	at junit.framework.TestCase.assertFalse(TestCase.java:219)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_delete_byIdx_empty_false(TestArrayList.java:202)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_delete_byIdx_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001">
      <failure>junit.framework.AssertionFailedError&#13;
	at junit.framework.Assert.fail(Assert.java:55)&#13;
	at junit.framework.Assert.assertTrue(Assert.java:22)&#13;
	at junit.framework.Assert.assertFalse(Assert.java:39)&#13;
	at junit.framework.Assert.assertFalse(Assert.java:47)&#13;
	at junit.framework.TestCase.assertFalse(TestCase.java:219)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_delete_byIdx_notEmpty_false(TestArrayList.java:225)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_delete_byIdx_notEmpty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_delete_byVal_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0">
      <error>java.lang.IndexOutOfBoundsException&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.checkOutOfBounds(ArrayListCopy.java:117)&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.delete(ArrayListCopy.java:47)&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.delete(ArrayListCopy.java:57)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_delete_byVal_empty_false(TestArrayList.java:261)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="test_delete_byVal_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0">
      <error>java.lang.IndexOutOfBoundsException&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.checkOutOfBounds(ArrayListCopy.java:117)&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.delete(ArrayListCopy.java:47)&#13;
	at bt.core.collections.dataTypes.ArrayListCopy.delete(ArrayListCopy.java:57)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_delete_byVal_notEmpty_false(TestArrayList.java:279)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</error>
    </testcase>
    <testcase name="test_delete_byVal_notEmpty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_get_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_get_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.053"/>
    <testcase name="test_get_notEmpty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001"/>
    <testcase name="test_indexOf_empty_m1" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_indexOf_notEmpty_0" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.002">
      <failure>java.lang.AssertionError: 
Expected: is &lt;-1&gt;
     but: was &lt;0&gt;&#13;
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)&#13;
	at org.junit.Assert.assertThat(Assert.java:956)&#13;
	at org.junit.Assert.assertThat(Assert.java:923)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_indexOf_notEmpty_0(TestArrayList.java:423)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_indexOf_notEmpty_m1" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_insert_on0_empty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_insert_on0_oneElInTape_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001"/>
    <testcase name="test_insert_on0_twoElInTape_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_insert_on1_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_insert_on1_oneElInTape_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_insert_on1_twoElInTape_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001">
      <failure>junit.framework.AssertionFailedError: expected same:&lt;null&gt; was not:&lt;2&gt;&#13;
	at junit.framework.Assert.fail(Assert.java:57)&#13;
	at junit.framework.Assert.failNotSame(Assert.java:325)&#13;
	at junit.framework.Assert.assertSame(Assert.java:288)&#13;
	at junit.framework.Assert.assertSame(Assert.java:296)&#13;
	at junit.framework.TestCase.assertSame(TestCase.java:465)&#13;
	at bt.tests.core.collections.dataTypes.TestArrayList.test_insert_on1_twoElInTape_true(TestArrayList.java:554)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at junit.framework.TestCase.runTest(TestCase.java:176)&#13;
	at junit.framework.TestCase.runBare(TestCase.java:141)&#13;
	at junit.framework.TestResult$1.protect(TestResult.java:122)&#13;
	at junit.framework.TestResult.runProtected(TestResult.java:142)&#13;
	at junit.framework.TestResult.run(TestResult.java:125)&#13;
	at junit.framework.TestCase.run(TestCase.java:129)&#13;
	at junit.framework.TestSuite.runTest(TestSuite.java:252)&#13;
	at junit.framework.TestSuite.run(TestSuite.java:247)&#13;
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test_insert_on3_twoElInTape_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_isEmpty_empty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_isEmpty_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_set_empty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_set_notEmpty_false" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_set_notEmpty_true" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.001"/>
    <testcase name="test_size_empty_0" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
    <testcase name="test_size_notEmpty_2" classname="bt.tests.core.collections.dataTypes.TestArrayList" time="0.0"/>
  </testsuite>
</testrun>
